name: Check-Node-Express
on: [push]
jobs:
  run-node-js-scripts:
    needs: run-shell-scripts-01
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16] # node 8 and node 10 not supproted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install Node Packages
        run: npm install

      - name: Run Basic Unit Test Script
        run: sh unit_tests/run-server-unit-test.sh
